workflows:
  ios-workflow:
    name: iOS IPA Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.pub-cache
        - ios/Pods
    scripts:
      - name: Set iOS deployment target
        script: |
          cd ios
          if ! grep -q "platform :ios, '15.0'" Podfile; then
            echo "platform :ios, '15.0'" | cat - Podfile > temp && mv temp Podfile
          fi
          cd ..
      - name: Clean and update CocoaPods
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..
      - name: Build IPA
        script: |
          flutter build ipa --release --no-tree-shake-icons
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.app
