// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUnWeH5ZIvemUREfrE2q1S_GOKtTjewC0',
    appId: '1:732670439433:android:56b41545e5c7d2ef5cc8d8',
    messagingSenderId: '732670439433',
    projectId: 'eduportal-69436',
    storageBucket: 'eduportal-69436.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlaAp7mfuP3FEjuealBb_OSm9MCmBlQgc',
    appId: '1:732670439433:ios:749b64d3eb3e7e7f5cc8d8',
    messagingSenderId: '732670439433',
    projectId: 'eduportal-69436',
    storageBucket: 'eduportal-69436.firebasestorage.app',
    androidClientId: '732670439433-dk55go1iq30pk193jtvgcg81bvu58n1v.apps.googleusercontent.com',
    iosClientId: '732670439433-9hkrocjp7eddeu159psb4f8p1itu8con.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsccoZsQbgzM1m6bCkB__9DJR6G575q9k',
    appId: '1:732670439433:web:91318dd0d11013a05cc8d8',
    messagingSenderId: '732670439433',
    projectId: 'eduportal-69436',
    authDomain: 'eduportal-69436.firebaseapp.com',
    storageBucket: 'eduportal-69436.firebasestorage.app',
    measurementId: 'G-CT52XT3JGS',
  );

}